- name: Commit and Push pass-data.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pass-data.json
          git stash
          git pull --rebase
          git stash pop || true
          git add pass-data.json
          git commit -m "Auto-update pass-data.json" || echo "No changes to commit"
          git push
